# Generated by Django 5.0.1 on 2024-12-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('config_type', models.CharField(choices=[('running', 'Running Config'), ('startup', 'Startup Config')], default='running', max_length=20)),
                ('content', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
